name: stemmer
description: A NLTK-port to perform stemming in Dart / Flutter and reduce words to its base.
version: 2.1.0
homepage: https://github.com/japborst/dart_stemmer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  test: ^1.16.8

dev_dependencies:
